version: '3'

volumes:
  pg_data_prod:
  static_volume:

services:
  db:
    container_name: taski_db_prod
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
  backend:
    container_name: taski_back_prod
    image: palacyris/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    container_name: taski_front_prod
    image: palacyris/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    container_name: taski_nginx_prod
    image: palacyris/taski_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
